"""
01_Extract_Cited_Cases_Batch.py
================================
Batch version of 01_Extracted_Cases.ipynb (Option B standalone pipeline).

For each judgment URL in the case index xlsx, extracts:
  - Cited case names (with years)
  - Surrounding citation paragraphs (±5 paragraphs context)

Input:  singapore_cases_complete_<TIMESTAMP>.xlsx  (from 00_Generate_Case_Index.py)
Output: 01_Extracted_Cases_Output/  (one xlsx per judgment)
        01_extracted_cases_progress.json  (checkpoint for resume)

Usage:
    pip install playwright beautifulsoup4 pandas openpyxl nest_asyncio tqdm
    playwright install chromium
    python 01_Extract_Cited_Cases_Batch.py
"""

import os
import json
import pandas as pd
from datetime import datetime
from tqdm import tqdm
from pathlib import Path

# ─────────────────────────── CONFIGURATION ───────────────────────────────────

# Input: case index file generated by 00_Generate_Case_Index.py
# Update this to match your actual filename
CASE_INDEX_FILE = "/Users/shannon/Desktop/singapore_cases_complete_20260311_163505.csv"

# Output single CSV file
OUTPUT_FILE     = "01_Extracted_Cases_Output.csv"

# Progress checkpoint file
PROGRESS_FILE   = "01_extracted_cases_progress.json"

# Max character length for cited case names (filters out garbage extractions)
MAX_CITED_CASE_NAME_LENGTH = 150

# Save progress every N judgments
SAVE_EVERY      = 10

# ─────────────────────────── CORE LIBRARY (from 01_Extracted_Cases.ipynb) ────
import asyncio
import nest_asyncio
import re
from dataclasses import dataclass
from typing import Optional, Tuple, List

from bs4 import BeautifulSoup, Tag
import pandas as pd

nest_asyncio.apply()

# ----------------------------
# NEW: Post-extraction whitespace normalization
# ----------------------------
def normalize_whitespace(text: str) -> str:
    """
    Normalize whitespace in text by:
    1. Converting all whitespace characters to regular spaces
    2. Collapsing multiple consecutive spaces to single spaces
    3. Stripping leading/trailing whitespace
    """
    if not text or pd.isna(text):
        return ""
    
    # Replace all types of whitespace with regular spaces
    # This includes: \t, \n, \r, \xa0 (non-breaking space), etc.
    normalized = re.sub(r'\s+', ' ', str(text))
    
    # Strip leading/trailing whitespace
    return normalized.strip()


def count_tokens(text: str) -> int:
    """
    Count the number of tokens/words in a text string.
    
    Args:
        text: The text to count tokens in
    
    Returns:
        Number of tokens (words) in the text
    """
    if not text or pd.isna(text):
        return 0
    
    # Split by whitespace and filter out empty strings
    tokens = re.split(r'\s+', str(text).strip())
    tokens = [token for token in tokens if token]  # Remove empty strings
    return len(tokens)


def filter_by_minimum_tokens(df: pd.DataFrame, min_tokens: int = 50, column: str = "Paragraph") -> pd.DataFrame:
    """
    Filter dataframe to remove rows where the specified column has fewer than min_tokens.
    Also removes cases where the paragraph is just the case name (insufficient context).
    
    Args:
        df: The dataframe to filter
        min_tokens: Minimum number of tokens required (default: 50 for substantial content)
        column: Column name to check token count (default: "Paragraph")
    
    Returns:
        Filtered dataframe with rows containing sufficient tokens and actual content
    """
    if column not in df.columns:
        return df
    
    # Count tokens for each row
    df['_token_count'] = df[column].apply(count_tokens)
    
    # Additional check: ensure paragraph contains more than just the case name
    def has_substantial_content(row):
        paragraph = str(row[column]).strip()
        case_name = str(row.get('Cited Case', '')).strip()
        
        # Remove the case name from paragraph to see what's left
        case_name_clean = re.sub(r'\s*\[.*?\]|\s*\(.*?\)', '', case_name).strip()
        
        # Check if paragraph is essentially just the case name
        if case_name_clean and len(case_name_clean) > 10:  # Only for substantial case names
            # If removing the case name leaves very little content, it's insufficient
            remaining_content = paragraph.replace(case_name_clean, '').strip()
            remaining_tokens = count_tokens(remaining_content)
            
            # Require at least 30 tokens beyond the case name
            return remaining_tokens >= 30
        
        return True  # For short case names, rely on token count only
    
    df['_has_content'] = df.apply(has_substantial_content, axis=1)
    
    # Filter to keep only rows with sufficient tokens AND substantial content
    filtered_df = df[(df['_token_count'] >= min_tokens) & (df['_has_content'])].copy()
    
    # Remove the temporary columns
    filtered_df = filtered_df.drop(columns=['_token_count', '_has_content'])
    
    return filtered_df

# ----------------------------
# Fetching (Playwright)
# ----------------------------
async def _fetch_html_async(url: str, wait_selector: Optional[str] = None) -> str:
    from playwright.async_api import async_playwright

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        page = await browser.new_page()  # ✅ Correct - browser has new_page()
        await page.goto(url)
        if wait_selector:
            await page.wait_for_selector(wait_selector)
        html = await page.content()
        await browser.close()
        return html

def fetch_html(url: str, wait_selector: Optional[str] = None) -> str:
    return asyncio.get_event_loop().run_until_complete(_fetch_html_async(url, wait_selector))

# ----------------------------
# Enhanced Config with Unreported Citations and Strong Tag Support
# ----------------------------
@dataclass
class ParserConfig:
    # Tags/classes considered as "italic-like" case title chunks
    # UPDATED: Added "strong" to support bold case names
    italic_tags: Tuple[str, ...] = ("span", "em", "i", "strong")
    italic_classes: Tuple[str, ...] = ("font-italic",)

    # Header containers and header text extraction - ENHANCED to include Judg-X content divs
    header_container_tags: Tuple[str, ...] = ("div", "p")
    header_container_classes: Tuple[str, ...] = (
        "Judg-1",           # ADDED: Regular judgment content paragraphs
        "Judg-2",           # ADDED: Continuation paragraphs
        "Judg-3",           # ADDED: Further continuation paragraphs  
        "Judg-Heading-1",
        "Judg-Heading-2",
        "Judg-Heading-3",
        "Judg-Heading-4",
        "Judg-Heading-5",
    )
    header_text_span_classes: Tuple[str, ...] = ("font-weight-bold",)

    # How many following siblings to scan to find year fragments
    lookahead_siblings: int = 10

    # Regexes for case detection
    versus_pattern: re.Pattern = re.compile(r"\s+v\.?\s+|\s+vs\.?\s+", re.IGNORECASE)
    re_title_pattern: re.Pattern = re.compile(r"^\s*(?:Re|In\s+re|In\s+the\s+matter\s+of)\b", re.IGNORECASE)
    
    # Singapore-style year patterns (unchanged)
    year_token_re: re.Pattern = re.compile(r"([\[(])\s*(\d{4})\s*([\])])")
    year_token_filter: re.Pattern = re.compile(r"[\[(]\s*\d{4}\s*[\])]")
    
    # US-style year patterns (unchanged)
    us_year_token_re: re.Pattern = re.compile(r"\(([^,)]+),\s*(\d{4})\)")
    us_year_token_filter: re.Pattern = re.compile(r"\([^,)]+,\s*\d{4}\)")

    # FIXED: Year range patterns - now handles en-dashes (–), em-dashes (—), and hyphens (-)
    year_range_token_re: re.Pattern = re.compile(r"([\[(])\s*(\d{4})[-–—∶']\s*(\d{4})\s*([\])])")
    year_range_token_filter: re.Pattern = re.compile(r"[\[(]\s*\d{4}[-–—∶']\s*\d{4}\s*[\])]")

    # Unreported citation patterns - TWO variants:
    # 1. With year: (Criminal Case No 16 of 2009, unreported)
    unreported_citation_re: re.Pattern = re.compile(r"\(([^)]*(\d{4})[^)]*),\s*unreported\)", re.IGNORECASE)
    unreported_citation_filter: re.Pattern = re.compile(r"\([^)]*\d{4}[^)]*,\s*unreported\)", re.IGNORECASE)
    
    # 2. Simple form: (Unreported) or (unreported) - NEW!
    simple_unreported_re: re.Pattern = re.compile(r"\(unreported\)", re.IGNORECASE)
    simple_unreported_filter: re.Pattern = re.compile(r"\(unreported\)", re.IGNORECASE)

# ----------------------------
# Enhanced Helpers
# ----------------------------

def is_italic_like(tag: Tag, cfg: ParserConfig) -> bool:
    if not isinstance(tag, Tag):
        return False
    # UPDATED: Now checks for "em", "i", and "strong" tags
    if tag.name in ("em", "i", "strong"):
        return True
    if tag.name == "span" and any(cls in (tag.get("class") or []) for cls in cfg.italic_classes):
        return True
    return False


def is_header_container(tag: Tag, cfg: ParserConfig) -> bool:
    if not isinstance(tag, Tag):
        return False
    if tag.name not in cfg.header_container_tags:
        return False
    classes = tag.get("class", [])
    return any(cls in classes for cls in cfg.header_container_classes)


def is_judg_content_div(tag: Tag) -> bool:
    """Check if a tag is a Judg content div (Judg-1, Judg-2, etc.) but not a heading"""
    if not isinstance(tag, Tag):
        return False
    if tag.name not in ("div", "p"):
        return False
    classes = tag.get("class", [])
    # Match Judg-1, Judg-2, etc. but not Judg-Heading-X
    return any(re.match(r"^Judg-\d+$", cls) for cls in classes)


def is_judg_quote_div(tag: Tag) -> bool:
    """Check if a tag is a Judg quote div (Judg-Quote-0, Judg-Quote-1, etc.)"""
    if not isinstance(tag, Tag):
        return False
    if tag.name not in ("div", "p"):
        return False
    classes = tag.get("class", [])
    # Match Judg-Quote-0, Judg-Quote-1, etc.
    return any(re.match(r"^Judg-Quote-\d+$", cls) for cls in classes)


def is_judg_heading_div(tag: Tag) -> bool:
    """Check if a tag is a Judg heading div (Judg-Heading-X)"""
    if not isinstance(tag, Tag):
        return False
    if tag.name not in ("div", "p"):
        return False
    classes = tag.get("class", [])
    return any("Judg-Heading" in cls for cls in classes)


def extract_focused_case_paragraph(italic_element: Tag, case_name: str, context_paragraphs: int = 5, include_quotes: bool = True) -> str:
    """
    ENHANCED: Extract the specific paragraph containing the case + surrounding context + optional quotes.
    Works with both Judg-X structured documents and plain paragraph documents.
    
    Args:
        italic_element: The italic element containing the case name
        case_name: The case name (for debugging)
        context_paragraphs: Number of paragraphs before/after to include (default: 5)
        include_quotes: Whether to include consecutive quote divs after context (default: True)
    
    Returns:
        Combined text with focused paragraph, context, and optional quotes
    """
    
    # Step 1: Find the containing paragraph - try Judg divs first, then fall back to p/div tags
    containing_div = italic_element
    while containing_div and not (is_judg_content_div(containing_div) or is_judg_quote_div(containing_div)):
        containing_div = containing_div.find_parent()
    
    # If no Judg div found, look for a regular paragraph or div container
    if not containing_div:
        containing_div = italic_element
        while containing_div and containing_div.name not in ('p', 'div', 'blockquote'):
            containing_div = containing_div.find_parent()
    
    if not containing_div:
        # Last resort fallback: get immediate parent text
        parent = italic_element.find_parent()
        return parent.get_text(" ", strip=True) if parent else ""
    
    # Step 2: Get text from the containing paragraph
    main_paragraph = containing_div.get_text(" ", strip=True)
    context_parts = [main_paragraph]
    
    # Step 3: Add context from surrounding paragraphs
    if context_paragraphs > 0:
        # Define what counts as a sibling paragraph
        def is_paragraph_like(t):
            if is_judg_content_div(t) or is_judg_quote_div(t):
                return True
            # For non-Judg documents, accept p, div, blockquote tags
            return isinstance(t, Tag) and t.name in ('p', 'div', 'blockquote') and t.get_text(strip=True)
        
        # Add previous paragraphs
        current = containing_div
        for _ in range(context_paragraphs):
            prev_div = current.find_previous_sibling(is_paragraph_like)
            if prev_div:
                context_parts.insert(0, prev_div.get_text(" ", strip=True))
                current = prev_div
            else:
                break
        
        # Add following paragraphs
        current = containing_div
        for _ in range(context_paragraphs):
            next_div = current.find_next_sibling(is_paragraph_like)
            if next_div:
                context_parts.append(next_div.get_text(" ", strip=True))
                current = next_div
            else:
                break
    
    # Step 4: ENHANCED - Include consecutive quote divs if enabled (primarily for Judg-X documents)
    if include_quotes:
        # Find the last element we've collected so far
        last_element = containing_div
        
        # If we added following paragraphs, find the actual last element
        if context_paragraphs > 0:
            temp_current = containing_div
            for _ in range(context_paragraphs):
                next_div = temp_current.find_next_sibling(lambda t: is_judg_content_div(t) or is_judg_quote_div(t))
                if next_div:
                    last_element = next_div
                    temp_current = next_div
                else:
                    break
        
        # Now continue from last_element to collect consecutive quote divs
        current = last_element
        while True:
            next_div = current.find_next_sibling(lambda t: is_judg_content_div(t) or is_judg_quote_div(t))
            if next_div and is_judg_quote_div(next_div):
                # Only add if it's a quote div and not already included
                quote_text = next_div.get_text(" ", strip=True)
                if quote_text not in context_parts:  # Avoid duplicates
                    context_parts.append(quote_text)
                current = next_div
            else:
                # Stop if we hit a non-quote div or no more divs
                break
    
    # Step 5: Combine and return
    combined_text = " ".join(context_parts)
    return normalize_whitespace(combined_text)


def normalize_brackets(open_b: str) -> str:
    return "]" if open_b == "[" else ")"


def remove_year(casename: str, cfg: ParserConfig) -> str:
    # Remove Singapore, US style, year range, and unreported years
    temp = re.sub(cfg.year_token_filter, "", casename)
    temp = re.sub(cfg.us_year_token_filter, "", temp)
    temp = re.sub(cfg.year_range_token_filter, "", temp)  
    temp = re.sub(cfg.unreported_citation_filter, "", temp)  # Remove unreported with year
    temp = re.sub(cfg.simple_unreported_filter, "", temp)   # NEW: Remove simple unreported
    return temp.strip()


def re_group_key(title: str) -> Optional[str]:
    m = re.match(r"^\s*(?:Re|In\s+re|In\s+the\s+matter\s+of)\s+(.+)$", title, re.IGNORECASE)
    if not m:
        return None
    body = m.group(1)
    tokens = re.findall(r"[A-Za-z0-9&][A-Za-z0-9&.'-]*", body)
    if not tokens:
        return None
    return ("re " + tokens[0].lower())

# ----------------------------
# NEW: Conservative Re Case Fix
# ----------------------------

def check_for_re_prefix(element: Tag) -> Optional[str]:
    """
    CONSERVATIVE: Only check for specific "Re " pattern immediately before italic span.
    Returns the "Re " prefix if found, None otherwise.
    """
    # Get the immediate previous sibling
    prev_sibling = element.previous_sibling
    
    if isinstance(prev_sibling, str):
        # Check if it ends with "Re " (with space)
        text = str(prev_sibling).strip()
        if text.endswith(" Re") or text.endswith("Re"):
            # Only return "Re" if it's clearly a case prefix
            if re.search(r'\bRe\s*$', text):
                return "Re"
    
    return None


def is_valid_case_with_re_check(full_case: str, first_italic_element: Tag, cfg: ParserConfig) -> Tuple[bool, str]:
    """
    Check if text is a valid case, with special handling for split "Re" cases.
    Returns (is_valid, final_case_name)
    """
    # First, try the original patterns (unchanged)
    if cfg.versus_pattern.search(full_case) or cfg.re_title_pattern.match(full_case):
        return True, full_case
    
    # ONLY if original patterns fail, check for "Re" prefix
    re_prefix = check_for_re_prefix(first_italic_element)
    if re_prefix:
        combined_case = f"{re_prefix} {full_case}".strip()
        # Verify the combined text matches Re pattern
        if cfg.re_title_pattern.match(combined_case):
            return True, combined_case
    
    return False, full_case


# ----------------------------
# NEW: Enhanced year search with parent sibling fallback
# ----------------------------

def collect_following_text(element: Tag, parent: Tag, children: List, i: int, cfg: ParserConfig) -> str:
    """
    Collect text following the element for year detection.
    First tries immediate siblings, then tries parent's siblings if element is nested.
    
    Args:
        element: The italic-like element containing the case name
        parent: The parent whose children we're iterating
        children: List of children of parent
        i: Current index in children
        cfg: Parser configuration
        
    Returns:
        Combined text window for year detection
    """
    window_texts: List[str] = []
    
    # Strategy 1: Look at immediate following siblings (original approach)
    for j in range(i, min(i + cfg.lookahead_siblings, len(children))):
        following = children[j]
        text = (
            following.get_text(" ", strip=True)
            if isinstance(following, Tag)
            else str(following)
        )
        window_texts.append(text)
    
    window = "".join(window_texts)
    
    # Strategy 2: If no year found, ALWAYS check element's parent's siblings
    # This handles cases like: <font><strong>Case</strong></font> <font>[YEAR]</font>
    if not (cfg.year_token_re.search(window) or 
            cfg.us_year_token_re.search(window) or
            cfg.year_range_token_re.search(window) or
            cfg.unreported_citation_re.search(window) or
            cfg.simple_unreported_re.search(window)):  # NEW: Check for simple unreported too
        
        # Get the element's immediate parent (e.g., the <font> tag)
        element_parent = element.parent
        
        if element_parent:
            # Look at this parent's following siblings
            parent_sibling_texts: List[str] = []
            current_sibling = element_parent.next_sibling
            sibling_count = 0
            
            while current_sibling and sibling_count < cfg.lookahead_siblings:
                if isinstance(current_sibling, Tag):
                    parent_sibling_texts.append(current_sibling.get_text(" ", strip=True))
                elif isinstance(current_sibling, str):
                    parent_sibling_texts.append(str(current_sibling))
                
                current_sibling = current_sibling.next_sibling
                sibling_count += 1
            
            if parent_sibling_texts:
                # Append parent sibling text to window
                window = window + " " + "".join(parent_sibling_texts)
    
    return window

# ----------------------------
# Core extraction - WITHOUT Header column
# ----------------------------

def extract_cases_from_soup(soup: BeautifulSoup, cfg: ParserConfig) -> pd.DataFrame:
    results = []
    processed_elements = set()  # Track processed elements to avoid duplicates

    # NEW APPROACH: Find all italic-like elements globally, regardless of nesting
    all_italic_elements = []
    for tag_name in cfg.italic_tags:
        all_italic_elements.extend(soup.find_all(tag_name))
    
    # Also find spans with italic classes
    for class_name in cfg.italic_classes:
        all_italic_elements.extend(soup.find_all("span", class_=class_name))
    
    for element in all_italic_elements:
        # Skip if already processed
        if id(element) in processed_elements:
            continue
        
        if not is_italic_like(element, cfg):
            continue
            
        first_italic_element = element
        italic_chunks = [element.get_text(" ", strip=True)]
        processed_elements.add(id(element))
        
        # Look for consecutive italic-like siblings to join multi-part case names
        current = element
        while True:
            next_sibling = current.next_sibling
            
            # Skip whitespace-only text nodes
            while next_sibling and isinstance(next_sibling, str) and next_sibling.strip() == "":
                next_sibling = next_sibling.next_sibling
            
            if next_sibling and isinstance(next_sibling, Tag) and is_italic_like(next_sibling, cfg):
                italic_chunks.append(next_sibling.get_text(" ", strip=True))
                processed_elements.add(id(next_sibling))
                current = next_sibling
            else:
                break
        
        full_case = " ".join(italic_chunks).strip()

        # ENHANCED: Use conservative Re case detection
        is_valid, final_case_name = is_valid_case_with_re_check(full_case, first_italic_element, cfg)

        if is_valid:
            # NEW: Enhanced year search with parent sibling fallback
            # Get siblings by looking at parent's children
            parent = element.parent
            if parent:
                children = list(parent.children)
                try:
                    element_index = children.index(element)
                    window = collect_following_text(element, parent, children, element_index + 1, cfg)
                except ValueError:
                    # Element not found in parent's children (shouldn't happen, but handle gracefully)
                    window = ""
            else:
                window = ""

            # Check for Singapore-style year first
            match = cfg.year_token_re.search(window)
            bracketed_year = None
            if match:
                open_b, yr, close_b = match.groups()
                bracketed_year = f"{open_b}{yr}{normalize_brackets(open_b)}"
            
            # Check for US-style year if no Singapore-style found
            if not bracketed_year:
                us_match = cfg.us_year_token_re.search(window)
                if us_match:
                    bracketed_year = us_match.group(0)

            # Check for year range if no other year found
            if not bracketed_year:
                year_range_match = cfg.year_range_token_re.search(window)
                if year_range_match:
                    open_b, start_yr, end_yr, close_b = year_range_match.groups()
                    bracketed_year = f"{open_b}{start_yr}-{end_yr}{normalize_brackets(open_b)}"

            # Check for unreported citations if no other year found
            if not bracketed_year:
                unreported_match = cfg.unreported_citation_re.search(window)
                if unreported_match:
                    bracketed_year = unreported_match.group(0)
            
            # NEW: Check for simple unreported (Unreported) if no other year found
            if not bracketed_year:
                simple_unreported_match = cfg.simple_unreported_re.search(window)
                if simple_unreported_match:
                    bracketed_year = simple_unreported_match.group(0)

            # Use the final_case_name (which might include "Re" prefix)
            case_output = f"{final_case_name} {bracketed_year}" if bracketed_year else final_case_name

            # ENHANCED: Extract focused paragraph with increased context and quote inclusion
            paragraph_block = extract_focused_case_paragraph(
                element, 
                case_output, 
                context_paragraphs=5,
                include_quotes=True
            )

            results.append({
                "Cited Case": case_output,
                "Paragraph": paragraph_block,
            })

    if not results:
        return pd.DataFrame(columns=["Cited Case", "Paragraph"])

    df = pd.DataFrame(results)

    # Check for Singapore, US style, year range, and unreported years
    has_singapore_year = df["Cited Case"].str.contains(cfg.year_token_filter, na=False)
    has_us_year = df["Cited Case"].str.contains(cfg.us_year_token_filter, na=False)
    has_year_range = df["Cited Case"].str.contains(cfg.year_range_token_filter, na=False)
    has_unreported = df["Cited Case"].str.contains(cfg.unreported_citation_filter, na=False)
    has_simple_unreported = df["Cited Case"].str.contains(cfg.simple_unreported_filter, na=False)  # NEW
    df["Has Year"] = has_singapore_year | has_us_year | has_year_range | has_unreported | has_simple_unreported  # NEW: Include simple unreported
    
    df["_is_re"] = df["Cited Case"].str.match(r"^\s*(?:Re|In\s+re|In\s+the\s+matter\s+of)\b", case=False)

    def base_group(x: str) -> Optional[str]:
        if not isinstance(x, str):
            return None
        return remove_year(x, cfg).lower()

    df["_group"] = df["Cited Case"].where(~df["_is_re"]).apply(base_group)

    re_keys = df.loc[df["_is_re"], "Cited Case"].apply(re_group_key)
    df.loc[df["_is_re"], "_group"] = re_keys

    # Simplified dedup key (no header)
    df["_dedup_key"] = df["_group"].astype(str)

    df.sort_values(by=["_dedup_key", "Has Year"], ascending=[True, False], inplace=True)

    clean_df = (
        df.drop_duplicates(subset=["_dedup_key"], keep="first")
          .drop(columns=["_group", "_dedup_key", "_is_re", "Has Year"])
    )

    # Filter to keep cases with Singapore, US style, year range, or unreported years
    has_singapore_year_final = clean_df["Cited Case"].str.contains(cfg.year_token_filter, na=False)
    has_us_year_final = clean_df["Cited Case"].str.contains(cfg.us_year_token_filter, na=False)
    has_year_range_final = clean_df["Cited Case"].str.contains(cfg.year_range_token_filter, na=False)
    has_unreported_final = clean_df["Cited Case"].str.contains(cfg.unreported_citation_filter, na=False)
    has_simple_unreported_final = clean_df["Cited Case"].str.contains(cfg.simple_unreported_filter, na=False)  # NEW
    clean_df = clean_df[has_singapore_year_final | has_us_year_final | has_year_range_final | has_unreported_final | has_simple_unreported_final].copy()

    # NEW: Post-extraction whitespace normalization
    for column in ["Cited Case", "Paragraph"]:
        if column in clean_df.columns:
            clean_df[column] = clean_df[column].apply(normalize_whitespace)
    
    # NEW: Filter out cases with insufficient paragraph content (< 50 tokens + substantial content check)
    # Prevents cases where paragraph is just the case name itself
    clean_df = filter_by_minimum_tokens(clean_df, min_tokens=50, column="Paragraph")
    
    return clean_df


def extract_cases_from_html(html: str, cfg: Optional[ParserConfig] = None) -> pd.DataFrame:
    cfg = cfg or ParserConfig()
    try:
        soup = BeautifulSoup(html, "html.parser")
    except Exception:
        soup = BeautifulSoup(html, "html.parser")
    return extract_cases_from_soup(soup, cfg)


def extract_cases_from_url(url: str, cfg: Optional[ParserConfig] = None, wait_selector: Optional[str] = None) -> pd.DataFrame:
    html = fetch_html(url, wait_selector=wait_selector)
    return extract_cases_from_html(html, cfg)

# ----------------------------
# Example usage with verification
# ----------------------------


# ─────────────────────────── PROGRESS ────────────────────────────────────────

def load_progress():
    if os.path.exists(PROGRESS_FILE):
        try:
            with open(PROGRESS_FILE) as f:
                return json.load(f)
        except Exception:
            pass
    return None

def save_progress(last_index: int, last_reference: str, successful: int, failed: int, failed_refs: list):
    with open(PROGRESS_FILE, "w") as f:
        json.dump({
            "last_index":     last_index,
            "last_reference": last_reference,
            "timestamp":      datetime.now().isoformat(),
            "successful":     successful,
            "failed":         failed,
            "failed_refs":    failed_refs
        }, f, indent=2)

def clear_progress():
    if os.path.exists(PROGRESS_FILE):
        os.remove(PROGRESS_FILE)

# ─────────────────────────── MAIN ────────────────────────────────────────────

def main():
    print("=" * 65)
    print("SG-LEGALCITE — STEP 1: EXTRACT CITED CASES (BATCH)")
    print("=" * 65)

    # Load case index
    print(f"\nReading case index: {CASE_INDEX_FILE}")
    df_cases = pd.read_csv(CASE_INDEX_FILE)
    print(f"Total judgments: {len(df_cases)}")

    # Check for previous progress
    start_idx   = 0
    successful  = 0
    failed      = 0
    failed_refs = []

    prev = load_progress()
    if prev:
        print(f"\nPrevious progress found:")
        print(f"  Last processed : #{prev['last_index']} — {prev['last_reference']}")
        print(f"  Successful     : {prev['successful']}")
        print(f"  Failed         : {prev['failed']}")
        print(f"  Timestamp      : {prev['timestamp']}")
        print(f"\nOptions:")
        print(f"  1. Resume from #{prev['last_index'] + 1}")
        print(f"  2. Retry failed cases ({prev['failed']} cases)")
        print(f"  3. Start fresh")
        choice = input("\nEnter choice (1/2/3): ").strip()

        if choice == "1":
            start_idx   = prev["last_index"] + 1
            successful  = prev["successful"]
            failed      = prev["failed"]
            failed_refs = prev.get("failed_refs", [])
            df_cases    = df_cases.iloc[start_idx:]
            print(f"  Resuming from index #{start_idx}")
        elif choice == "2":
            failed_refs = prev.get("failed_refs", [])
            df_cases    = df_cases[df_cases["Full_Reference"].isin(failed_refs)]
            successful  = prev["successful"]
            failed      = 0
            failed_refs = []
            print(f"  Retrying {len(df_cases)} failed cases")
        else:
            clear_progress()
            print("  Starting fresh.")

    # Create output CSV with header if starting fresh
    if start_idx == 0 and not prev:
        with open(OUTPUT_FILE, 'w') as f:
            pass  # clear file

    cfg = ParserConfig()
    first_write = not os.path.exists(OUTPUT_FILE) or os.path.getsize(OUTPUT_FILE) == 0

    try:
        for i, (_, row) in enumerate(tqdm(df_cases.iterrows(), total=len(df_cases), desc="Extracting")):
            url       = row["URL"]
            ref       = row["Full_Reference"]
            abs_idx   = start_idx + i

            try:
                df_out = extract_cases_from_url(url, cfg)

                if df_out is not None and len(df_out) > 0:
                    # Filter out cited case names that are too long (garbage extractions)
                    before = len(df_out)
                    df_out = df_out[df_out['Cited Case'].astype(str).str.len() <= MAX_CITED_CASE_NAME_LENGTH]
                    filtered = before - len(df_out)

                    if filtered > 0 and len(df_out) > 0:
                        tqdm.write(f"  ✓ {ref}: {len(df_out)} cited cases extracted ({filtered} oversized filtered)")
                    elif filtered > 0 and len(df_out) == 0:
                        tqdm.write(f"  ⚠ {ref}: 0 cited cases after filtering {filtered} oversized names")
                    else:
                        tqdm.write(f"  ✓ {ref}: {len(df_out)} cited cases extracted")

                    # Add source judgment metadata
                    df_out.insert(0, "Judgment_URL",       url)
                    df_out.insert(1, "Judgment_Reference", ref)
                    df_out.insert(2, "Year",               row["Year"])
                    df_out.insert(3, "Court_Type",         row["Court_Type"])
                    df_out.insert(4, "Case_Number",        row["Case_Number"])

                    # Append to CSV (write header only on first write)
                    df_out.to_csv(OUTPUT_FILE, mode='a', header=first_write, index=False)
                    first_write = False
                    successful += 1
                else:
                    tqdm.write(f"  ⚠ No citations found: {ref}")
                    failed_refs.append(ref)
                    failed += 1

            except Exception as e:
                tqdm.write(f"  ✗ Error processing {ref}: {str(e)[:100]}")
                failed_refs.append(ref)
                failed += 1

            # Save progress every SAVE_EVERY judgments
            if (i + 1) % SAVE_EVERY == 0:
                save_progress(abs_idx, ref, successful, failed, failed_refs)

    except KeyboardInterrupt:
        print("\n\n⚠ Interrupted — saving progress...")
        save_progress(abs_idx, ref, successful, failed, failed_refs)

    # Final save
    save_progress(abs_idx, ref, successful, failed, failed_refs)

    print("\n" + "=" * 65)
    print("COMPLETE")
    print("=" * 65)
    print(f"Successful : {successful}")
    print(f"Failed     : {failed}")
    print(f"Output     : {OUTPUT_FILE}")

    if failed_refs:
        print(f"\nFailed cases:")
        for r in failed_refs:
            print(f"  - {r}")


if __name__ == "__main__":
    main()
